# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoapodsDemo
  pod 'DebugSettings', :path => '../../DebugSettings.podspec'
  
  # [LookIn官网](https://lookin.work/)
  pod 'LookinServer', :configurations => ['Debug']
end
