# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoapodsDemo
  pod 'DebugSettings', :path => '../../DebugSettings.podspec'
  
  # [LookIn官网](https://lookin.work/)
  pod 'LookinServer', :configurations => ['Debug']
end

# This is necessary for Xcode 14, because it signs resource bundles by default
# when building for devices.
post_install do |installer|
  installer.target_installation_results.pod_target_installation_results
  .each do |pod_name, target_installation_result|
    target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
      resource_bundle_target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
